announcement:
  statuses:
    - enabled
    - disabled

order:
  statuses:
    - reviewing
    - reviewed
    - confirmed
    - received_usa_hub
    - paid
    - out_for_delivery
    - delivered
    - on_hold
    - returned
    - cancelled

notification:
  statuses:
    - unread
    - read

transaction:
  transaction_types:
    - addition
    - deduction
    - paid_by_cash
